name: Setup databaseab
description: Set up Node 20 and optionally install ffprobe

inputs:
  install-ffprobe:
    description: 'Whether to install ffprobe'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install ffprobe
      if: inputs.install-ffprobe == 'true'
      shell: bash
      run: |
        sudo apt-get install -y --no-install-recommends ffmpeg
        ffprobe -version
